data/example/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('', include('tgi.urls')),
    path('admin/', admin.site.urls),
]

data/tgi/urls.py
from django.urls import path

from . import views

app_name = 'tgi'
urlpatterns = [
    path('', views.index, name='index'),
	path('search/', views.search, name='search'),
	path('detail', views.detail, name='detail'),
	path('clasif/', views.clasif, name='clasif'),
	path('classification/', views.classification, name='classification'),
	path('search/<int:search_id>', views.result, name='result'),
]

data/tgi/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class SearchModel(models.Model):
	search_text = models.CharField(max_length=200)
	date_search = models.DateTimeField('date searched')

class Tweet(models.Model):
	text = models.CharField(max_length=800)
	author = models.CharField(max_length=20)
	pub_date = models.DateTimeField('date published')
	classif = models.CharField(max_length=5)
	search = models.ForeignKey(SearchModel, on_delete=models.CASCADE)
	
class Hashtag(models.Model):
	hashtag_text = models.CharField(max_length=200)
	tweets = models.ManyToManyField(Tweet)
	
	def __str__(self):
		return self.hashtag_text

data/tgi/views.py
from __future__ import print_function
from __future__ import unicode_literals

from builtins import str, bytes, dict, int
from builtins import range

import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

from pattern.web import Twitter, hashtags
from pattern.db import Datasheet, pprint, pd
from pattern.search import search
from pattern.vector import Document, Model, KNN
from pattern.en import Sentence, parse

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone

from .models import SearchModel, Tweet, Hashtag
import datetime

# Create your views here.

def index(request):
	return render(request, 'tgi/index.html')

def clasif(request):
	searches = SearchModel.objects.all()
	return render(request, 'tgi/clasif.html', {'searches': searches})
	
def classification(request):
	try:
		selected_search = SearchModel.objects.get(pk=request.POST['choice'])
	except (KeyError, SearchModel.DoesNotExist):
		return render(request, 'tgi/clasif.html', {
			'error_message': "No se ha elegido ninguna busqueda",
		})
	else:
		
		try:
			classifier = KNN.load(os.path.join(os.path.dirname(__file__), "classifier"))
		except:
			return render(request, 'tgi/clasif.html', {
				'error_message': "El clasificador no ha sido entrenado",
			})
		else:
			for tweet in selected_search.tweet_set.all():
				tweet.classif = classifier.classify(tweet.text)
				if tweet.classif == None:
					tweet.classif = "NaN"
				tweet.save()
			
			return render(request, 'tgi/classification.html', {'search': selected_search, 'classifier': classifier})
		
def detail(request):
	try:		
		classifier = KNN.load(os.path.join(os.path.dirname(__file__),  "classifier"))
	except:
		return render(request, 'tgi/detail.html', {
				'error_message': "El clasificador no existe",
				'classifier': classifier,
				'size': str(len(classifier.features)),
			})
	else:
		return render(request, 'tgi/detail.html', {'classifier': classifier, 'size': len(classifier.features)})

def search(request):

	try:
		newSearch = SearchModel.objects.get(search_text=request.POST['search'])
	except:
		newSearch = SearchModel(search_text=request.POST['search'], date_search=timezone.now())		
	else:
		newSearch.date_search = timezone.now()
		newSearch.tweet_set.all().delete()
	
	newSearch.save()
		
	engine = Twitter(language="en")
	prev = None
	index = set()
	
	for i in range(2):
		for tweet in engine.search(request.POST['search'], start=prev, count=10, cached=False):
			if tweet.id not in index:
				date = datetime.datetime.strptime(tweet.date, '%a %b %d %H:%M:%S %z %Y').strftime('%Y-%m-%d %H:%M')
				
				newTweet = newSearch.tweet_set.create(text=tweet.text, author=tweet.author, pub_date=date)
				
				hashes = hashtags(tweet.text)
				for hashtag in hashes:
					try:
						newHashtag = Hashtag.objects.get(hashtag_text=hashtag)
					except:
						newHashtag = Hashtag(hashtag_text=hashtag)
						newHashtag.save()
					
					newHashtag.tweets.add(newTweet)
				
				index.add(tweet.id)
				
			prev = tweet.id
	
	return HttpResponseRedirect(reverse('tgi:result', args=[newSearch.id]))
	
def result(request, search_id):
	search = get_object_or_404(SearchModel, pk=search_id)
	return render(request, 'tgi/result.html', {'search': search})
	

data/tgi/templates/tgi/clasif.html
{% load static %}
<HTML>
	<HEAD>
		<link rel="stylesheet" type="text/css" href="{% static 'tgi/css/bootstrap.min.css' %}">
	</HEAD>
	<BODY>
	<!-- NAVBAR -->
		<NAV class="navbar navbar-expand-sm bg-dark navbar-dark">
			<A class="navbar-brand" href="{% url 'tgi:index' %}">Inicio</A>
			<UL class="navbar-nav">
				<LI class="nav-item">
					<A class="nav-link" href="{% url 'tgi:detail' %}">Detalles del Clasificador</A>
				</LI>
				<LI class="nav-item">
					<A class="nav-link" href="{% url 'tgi:clasif' %}">Clasificar Busquedas</A>
				</LI>
			</UL>
		</NAV>
		
	<!-- CUERPO PAGINA -->
		<br>
		<DIV class="jumbotron container">
			{% if error_message %}
			<DIV class="alert alert-warning" role="alert">
				{{ error_message }}
			</DIV>
			{% endif %}
			<FORM class="form-inline justify-content-center" action="{% url 'tgi:classification' %}" method="post">
			{% csrf_token %}
				<DIV class="form-group">
					<LABEL for="choice" class="mr-sm-2" >Select the search you wish to classify</LABEL>
					<SELECT class="form-control mb-2 mr-sm-2" id="choice" name="choice">
						{% for search in searches %}
							<OPTION value="{{ search.id }}">{{ search.search_text }}</OPTION>
						{% endfor %}
					</SELECT>
				</DIV>
				<BUTTON type="submit" class="btn btn-primary mb-2">Classify</BUTTON>
			</FORM>
		</DIV>
	</BODY>
	<FOOTER >
		<P class="text-center">&copy; Copyright 2019 Pierre Simon Callist Yannick Tondreau</P>
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
		<script src="{% static 'tgi/js/bootstrap.min.js' %}"></script>
	</FOOTER>
</HTML>

data/tgi/templates/tgi/classification.html
{% load static %}
<HTML>
	<HEAD>
		<link rel="stylesheet" type="text/css" href="{% static 'tgi/css/bootstrap.min.css' %}">
	</HEAD>
	<BODY>
	<!-- NAVBAR -->
		<NAV class="navbar navbar-expand-sm bg-dark navbar-dark">
			<A class="navbar-brand" href="{% url 'tgi:index' %}">Inicio</A>
			<UL class="navbar-nav">
				<LI class="nav-item">
					<A class="nav-link" href="{% url 'tgi:detail' %}">Detalles del Clasificador</A>
				</LI>
				<LI class="nav-item">
					<A class="nav-link" href="{% url 'tgi:clasif' %}">Clasificar Busquedas</A>
				</LI>
			</UL>
		</NAV>
		
	<!-- CUERPO PAGINA -->
		<DIV class="container">
		<H1 class="text-center">Resultados de la clasificaci&oacute;n: </H1> 
		<H2 class="text-center">{{ search.search_text }}</H2>
		<TABLE class="table table-striped">
			<THEAD>
				<TR>
					<TH>Author</TH>
					<TH>Text</TH>
					<TH>Hashtags</TH>
					<TH>Classification</TH>
				</TR>
			</THEAD>
			<TBODY>
				{% for tweet in search.tweet_set.all %}
					<TR>
						<TD>{{ tweet.author }}</TD>
						<TD>{{ tweet.text }}</TD>
						<TD>
							{% for hashtag in tweet.hashtag_set.all %}
								{{ hashtag.hashtag_text }}
							{% endfor %}
						</TD>
						{% if tweet.classif == "WIN" %}
							<TD>GOOD</TD>
						{% elif tweet.classif == "FAIL" %}
							<TD>BAD</TD>
						{% else %}
							<TD>N/A</TD>
						{% endif %}
					</TR>
				{% endfor %}
		</TABLE>
		</DIV>
	</BODY>
	<FOOTER>
		<P class="text-center">&copy; Copyright 2019 Pierre Simon Callist Yannick Tondreau</P>
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
		<script src="{% static 'tgi/js/bootstrap.min.js' %}"></script>
	</FOOTER>
</HTML>

data/tgi/templates/tgi/detail.html
{% load static %}
<HTML>
	<HEAD>
		<link rel="stylesheet" type="text/css" href="{% static 'tgi/css/bootstrap.min.css' %}">
	</HEAD>
	<BODY>
	<!-- NAVBAR -->
		<NAV class="navbar navbar-expand-sm bg-dark navbar-dark">
			<A class="navbar-brand" href="{% url 'tgi:index' %}">Inicio</A>
			<UL class="navbar-nav">
				<LI class="nav-item">
					<A class="nav-link" href="{% url 'tgi:detail' %}">Detalles del Clasificador</A>
				</LI>
				<LI class="nav-item">
					<A class="nav-link" href="{% url 'tgi:clasif' %}">Clasificar Busquedas</A>
				</LI>
			</UL>
		</NAV>
		
	<!-- CUERPO PAGINA -->
		<br>
		<DIV class="jumbotron container">
			{% if error_message %}
			<DIV class="alert alert-warning" role="alert">
				{{ error_message }}
			</DIV>
			{% endif %}
			<H2>Detalles del clasificador</H2>
			<A><strong>Palabras entrenadas:</strong></A><A> {{ size }}</A><br>
			<A><strong>Skewness:</strong></A><A> {{ classifier.skewness }}</A>
		</DIV>
	</BODY>
	<FOOTER >
		<P class="text-center">&copy; Copyright 2019 Pierre Simon Callist Yannick Tondreau</P>
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
		<script src="{% static 'tgi/js/bootstrap.min.js' %}"></script>
	</FOOTER>
</HTML>

data/tgi/templates/tgi/index.html
{% load static %}
<HTML>
	<HEAD>
		<link rel="stylesheet" type="text/css" href="{% static 'tgi/css/bootstrap.min.css' %}">
	</HEAD>
	<BODY>
	<!-- NAVBAR -->
		<NAV class="navbar navbar-expand-sm bg-dark navbar-dark">
			<A class="navbar-brand" href="{% url 'tgi:index' %}">Inicio</A>
			<UL class="navbar-nav">
				<LI class="nav-item">
					<A class="nav-link" href="{% url 'tgi:detail' %}">Detalles del Clasificador</A>
				</LI>
				<LI class="nav-item">
					<A class="nav-link" href="{% url 'tgi:clasif' %}">Clasificar Busquedas</A>
				</LI>
			</UL>
		</NAV>
		
	<!-- CUERPO PAGINA -->
		<br>
		<DIV class="jumbotron container">
			<FORM class="form-inline justify-content-center" action="{% url 'tgi:search' %}" method="post">
			{% csrf_token %}
				<LABEL for="search" class="mr-sm-2" >Search:</LABEL>
				<INPUT type="text" class="form-control  mb-2 mr-sm-2" name="search" placeholder="Search">
				<BUTTON type="submit" class="btn btn-primary mb-2">Submit</BUTTON>
			</FORM>
		</DIV>
	</BODY>
	<FOOTER >
		<P class="text-center">&copy; Copyright 2019 Pierre Simon Callist Yannick Tondreau</P>
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
		<script src="{% static 'tgi/js/bootstrap.min.js' %}"></script>
	</FOOTER>
</HTML>

data/tgi/templates/tgi/result.html
{% load static %}
<HTML>
	<HEAD>
		<link rel="stylesheet" type="text/css" href="{% static 'tgi/css/bootstrap.min.css' %}">
	</HEAD>
	<BODY>
	<!-- NAVBAR -->
		<NAV class="navbar navbar-expand-sm bg-dark navbar-dark">
			<A class="navbar-brand" href="{% url 'tgi:index' %}">Test</A>
			<UL class="navbar-nav">
				<LI class="nav-item">
					<A class="nav-link" href="{% url 'tgi:detail' %}">Detalles del Clasificador</A>
				</LI>
				<LI class="nav-item">
					<A class="nav-link" href="{% url 'tgi:clasif' %}">Clasificar Busquedas</A>
				</LI>
			</UL>
		</NAV>
		
	<!-- CUERPO PAGINA -->
		<DIV class="container">
		<H1 class="text-center">Resultados de la b&uacute;squeda: </H1> 
		<H2 class="text-center">{{ search.search_text }}</H2>
		<TABLE class="table table-striped">
			<THEAD>
				<TR>
					<TH>Author</TH>
					<TH>Text</TH>
					<TH>Hashtags</TH>
					<TH>Date Published</TH>
				</TR>
			</THEAD>
			<TBODY>
				{% for tweet in search.tweet_set.all %}
					<TR>
						<TD>{{ tweet.author }}</TD>
						<TD>{{ tweet.text }}</TD>
						<TD>
							{% for hashtag in tweet.hashtag_set.all %}
								{{ hashtag.hashtag_text }}
							{% endfor %}
						</TD>
						<TD>{{ tweet.pub_date }}</TD>
					</TR>
				{% endfor %}
		</TABLE>
		</DIV>
	</BODY>
	<FOOTER>
		<P class="text-center">&copy; Copyright 2019 Pierre Simon Callist Yannick Tondreau</P>
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
		<script src="{% static 'tgi/js/bootstrap.min.js' %}"></script>
	</FOOTER>
</HTML>

data/tgi/templates/tgi/train.html
{% load static %}
<HTML>
	<HEAD>
		<link rel="stylesheet" type="text/css" href="{% static 'tgi/css/bootstrap.min.css' %}">
	</HEAD>
	<BODY>
	<!-- NAVBAR -->
		<NAV class="navbar navbar-expand-sm bg-dark navbar-dark">
			<A class="navbar-brand" href="{% url 'tgi:index' %}">Inicio</A>
			<UL class="navbar-nav">
				<LI class="nav-item">
					<A class="nav-link" href="{% url 'tgi:detail' %}">Detalles del Clasificador</A>
				</LI>
				<LI class="nav-item">
					<A class="nav-link" href="{% url 'tgi:clasif' %}">Clasificar Busquedas</A>
				</LI>
			</UL>
		</NAV>
		
	<!-- CUERPO PAGINA -->
		<br>
		<DIV class="jumbotron container">
			{% if error_message %}
			<DIV class="alert alert-warning" role="alert">
				{{ error_message }}
			</DIV>
			{% endif %}
			<FORM class="form-inline justify-content-center" action="{% url 'tgi:training' %}" method="post">
			{% csrf_token %}
				<BUTTON type="submit" class="btn btn-primary  mb-2">Train</BUTTON>
			</FORM>
		</DIV>
	</BODY>
	<FOOTER >
		<P class="text-center">&copy; Copyright 2019 Pierre Simon Callist Yannick Tondreau</P>
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
		<script src="{% static 'tgi/js/bootstrap.min.js' %}"></script>
	</FOOTER>
</HTML>